platform :ios, '7.0'

pod 'Reachability'
pod 'CustomBadge'
pod 'ISO8601DateFormatter'
pod 'RestKit'
pod 'Mantle'
#pod 'JSONKit'
pod 'AJNotificationView'
pod 'NSData+Base64'
pod 'OpenSSL-Universal', '1.0.1.k'
