platform :ios, '7.0'

pod 'SCNetworkReachability'
pod 'CustomBadge'
pod 'ISO8601DateFormatter'
pod 'AFNetworking'
pod 'Mantle'
pod 'ALAlertBanner'
pod 'NSData+Base64'
pod 'OpenSSL-Universal', '1.0.1.k'
